package table

import java.io.{InputStream, Reader}
import java.net.URL
import java.sql._
import java.util.concurrent.Executor
import java.util.{Calendar, Properties}
import java.{sql, util}

object Mockup {

  class LoggingPreparedStatement extends PreparedStatement {

    def log(msg: String): Unit = println(s"\t\t[Mock.Stmt] $msg")

    override def addBatch(): Unit = log("addBatch()")
    override def addBatch(sql: String): Unit = log(s"addBatch(sql=$sql)")

    override def cancel(): Unit = log("cancel()")
    override def clearBatch(): Unit = log("clearBatch()")
    override def clearParameters(): Unit = log("clearParameters()")
    override def clearWarnings(): Unit = log("clearWarnings()")
    override def close(): Unit = log("close()")
    override def closeOnCompletion(): Unit = log("closeOnCompletion()")

    override def execute(): Boolean = {
      log("execute()"); false
    }

    override def execute(sql: String): Boolean = {
      log(s"execute(sql=$sql)"); false
    }

    override def execute(sql: String, autoGeneratedKeys: Int): Boolean = {
      log(s"execute(sql=$sql, autoGeneratedKeys=$autoGeneratedKeys)"); false
    }

    override def execute(sql: String, columnIndexes: scala.Array[Int]): Boolean = {
      log(s"execute(sql=$sql, columnIndexes=${columnIndexes.mkString(",")})"); false
    }

    override def execute(sql: String, columnNames: scala.Array[String]): Boolean = {
      log(s"execute(sql=$sql, columnNames=${columnNames.mkString(",")})"); false
    }

    override def executeBatch(): scala.Array[Int] = {
      log("executeBatch()"); scala.Array.empty
    }

    override def executeQuery(): ResultSet = {
      log("executeQuery()"); null
    }

    override def executeQuery(sql: String): ResultSet = {
      log(s"executeQuery(sql=$sql)"); null
    }

    override def executeUpdate(): Int = {
      log("executeUpdate()"); 0
    }

    override def executeUpdate(sql: String): Int = {
      log(s"executeUpdate(sql=$sql)"); 0
    }

    override def executeUpdate(sql: String, autoGeneratedKeys: Int): Int = {
      log(s"executeUpdate(sql=$sql, autoGeneratedKeys=$autoGeneratedKeys)"); 0
    }

    override def executeUpdate(sql: String, columnIndexes: scala.Array[Int]): Int = {
      log(s"executeUpdate(sql=$sql, columnIndexes=${columnIndexes.mkString(",")})"); 0
    }

    override def executeUpdate(sql: String, columnNames: scala.Array[String]): Int = {
      log(s"executeUpdate(sql=$sql, columnNames=${columnNames.mkString(",")})"); 0
    }

    override def getConnection: Connection = {
      log("getConnection() : not supported in Mock-up"); null    // todo
    }

    override def getFetchDirection: Int = {
      log("getFetchDirection()"); 0
    }

    override def getFetchSize: Int = {
      log("getFetchSize()"); 0
    }

    override def getGeneratedKeys: ResultSet = {
      log("getGeneratedKeys()"); null
    }

    override def getMaxFieldSize: Int = {
      log("getMaxFieldSize()"); 0
    }

    override def getMaxRows: Int = {
      log("getMaxRows()"); 0
    }

    override def getMetaData: ResultSetMetaData = {
      log("getMetaData()"); null
    }

    override def getMoreResults(current: Int): Boolean = {
      log(s"getMoreResults(current=$current)"); false
    }

    override def getMoreResults: Boolean = {
      log("getMoreResults()"); false
    }

    override def getParameterMetaData: ParameterMetaData = {
      log("getParameterMetaData()"); null
    }

    override def getQueryTimeout: Int = {
      log("getQueryTimeout()"); 0
    }

    override def getResultSet: ResultSet = {
      log("getResultSet()"); null
    }

    override def getResultSetConcurrency: Int = {
      log("getResultSetConcurrency()"); 0
    }

    override def getResultSetHoldability: Int = {
      log("getResultSetHoldability()"); 0
    }

    override def getResultSetType: Int = {
      log("getResultSetType()"); 0
    }

    override def getUpdateCount: Int = {
      log("getUpdateCount()"); 0
    }

    override def getWarnings: SQLWarning = {
      log("getWarnings()"); null
    }

    override def isCloseOnCompletion: Boolean = {
      log("isCloseOnCompletion()"); false
    }

    override def isClosed: Boolean = {
      log("isClosed()"); false
    }

    override def isPoolable: Boolean = {
      log("isPoolable()"); false
    }

    override def isWrapperFor(iface: Class[_]): Boolean = {
      log(s"isWrapperFor($iface)"); false
    }

    override def setArray(i: Int, x: sql.Array): Unit = log(s"setArray($i, $x)")

    override def setAsciiStream(i: Int, x: InputStream): Unit = log(s"setAsciiStream($i, $x)")

    override def setAsciiStream(i: Int, x: InputStream, length: Int): Unit = log(s"setAsciiStream($i, length=$length)")

    override def setAsciiStream(i: Int, x: InputStream, length: Long): Unit = log(s"setAsciiStream($i, length=$length)")

    override def setBigDecimal(i: Int, x: java.math.BigDecimal): Unit = log(s"setBigDecimal($i, $x)")

    override def setBinaryStream(i: Int, x: InputStream): Unit = log(s"setBinaryStream($i, $x)")

    override def setBinaryStream(i: Int, x: InputStream, length: Int): Unit = log(s"setBinaryStream($i, length=$length)")

    override def setBinaryStream(i: Int, x: InputStream, length: Long): Unit = log(s"setBinaryStream($i, length=$length)")

    override def setBlob(i: Int, inputStream: InputStream): Unit = log(s"setBlob($i, $inputStream)")

    override def setBlob(i: Int, inputStream: InputStream, length: Long): Unit = log(s"setBlob($i, inputStream, length=$length)")

    override def setBlob(i: Int, x: Blob): Unit = log(s"setBlob($i, $x)")

    override def setBoolean(i: Int, x: Boolean): Unit = log(s"setBoolean($i, $x)")

    override def setByte(i: Int, x: Byte): Unit = log(s"setByte($i, $x)")

    override def setBytes(i: Int, x: scala.Array[Byte]): Unit = log(s"setBytes($i, length=${x.length})")

    override def setCharacterStream(i: Int, reader: Reader): Unit = log(s"setCharacterStream($i, $reader)")

    override def setCharacterStream(i: Int, reader: Reader, length: Int): Unit = log(s"setCharacterStream($i, length=$length)")

    override def setCharacterStream(i: Int, reader: Reader, length: Long): Unit = log(s"setCharacterStream($i, reader, length=$length)")

    override def setClob(i: Int, reader: Reader): Unit = log(s"setClob($i, $reader)")

    override def setClob(i: Int, reader: Reader, length: Long): Unit = log(s"setClob($i, reader, length=$length)")

    override def setClob(i: Int, x: Clob): Unit = log(s"setClob($i, $x)")

    override def setCursorName(name: String): Unit = log(s"setCursorName($name)")

    override def setDate(i: Int, x: Date): Unit = log(s"setDate($i, $x)")

    override def setDate(i: Int, x: Date, cal: Calendar): Unit = log(s"setDate($i, $x, cal=$cal)")

    override def setDouble(i: Int, x: Double): Unit = log(s"setDouble($i, $x)")

    override def setEscapeProcessing(enable: Boolean): Unit = log(s"setEscapeProcessing($enable)")

    override def setFetchDirection(direction: Int): Unit = log(s"setFetchDirection($direction)")

    override def setFetchSize(rows: Int): Unit = log(s"setFetchSize($rows)")

    override def setFloat(i: Int, x: Float): Unit = log(s"setFloat($i, $x)")

    override def setInt(i: Int, x: Int): Unit = log(s"setInt($i, $x)")

    override def setLong(i: Int, x: Long): Unit = log(s"setLong($i, $x)")

    override def setMaxFieldSize(max: Int): Unit = log(s"setMaxFieldSize($max)")

    override def setMaxRows(max: Int): Unit = log(s"setMaxRows($max)")

    override def setNCharacterStream(i: Int, value: Reader): Unit = log(s"setNCharacterStream($i, $value)")

    override def setNCharacterStream(i: Int, value: Reader, length: Long): Unit = log(s"setNCharacterStream($i, length=$length)")

    override def setNClob(i: Int, reader: Reader): Unit = log(s"setNClob($i, $reader)")

    override def setNClob(i: Int, reader: Reader, length: Long): Unit = log(s"setNClob($i, reader, length=$length)")

    override def setNClob(i: Int, value: NClob): Unit = log(s"setNClob($i, $value)")

    override def setNString(i: Int, value: String): Unit = log(s"setNString($i, $value)")

    override def setNull(i: Int, sqlType: Int): Unit = log(s"setNull($i, $sqlType)")

    override def setNull(i: Int, sqlType: Int, typeName: String): Unit = log(s"setNull($i, $sqlType, typeName=$typeName)")

    override def setObject(i: Int, x: Any): Unit = log(s"setObject($i, $x)")

    override def setObject(i: Int, x: Any, targetSqlType: Int): Unit = log(s"setObject($i, $x, targetSqlType=$targetSqlType)")

    override def setObject(i: Int, x: Any, targetSqlType: Int, scaleOrLength: Int): Unit = log(s"setObject($i, $x, targetSqlType=$targetSqlType, scaleOrLength=$scaleOrLength)")

    override def setPoolable(poolable: Boolean): Unit = log(s"setPoolable($poolable)")

    override def setQueryTimeout(seconds: Int): Unit = log(s"setQueryTimeout($seconds)")

    override def setRef(i: Int, x: Ref): Unit = log(s"setRef($i, $x)")

    override def setRowId(i: Int, x: RowId): Unit = log(s"setRowId($i, $x)")

    override def setSQLXML(i: Int, xmlObject: SQLXML): Unit = log(s"setSQLXML($i, $xmlObject)")

    override def setShort(i: Int, x: Short): Unit = log(s"setShort($i, $x)")

    override def setString(i: Int, x: String): Unit = log(s"setString($i, $x)")

    override def setTime(i: Int, x: Time): Unit = log(s"setTime($i, $x)")

    override def setTime(i: Int, x: Time, cal: Calendar): Unit = log(s"setTime($i, $x, cal=$cal)")

    override def setTimestamp(i: Int, x: Timestamp): Unit = log(s"setTimestamp($i, $x)")

    override def setTimestamp(i: Int, x: Timestamp, cal: Calendar): Unit = log(s"setTimestamp($i, $x, cal=$cal)")

    override def setURL(i: Int, x: URL): Unit = log(s"setURL($i, $x)")

    override def setUnicodeStream(i: Int, x: InputStream, length: Int): Unit = log(s"setUnicodeStream($i, length=$length)")

    override def unwrap[T](iface: Class[T]): T = {
      log(s"unwrap($iface)"); null.asInstanceOf[T]
    }
  }

  class LoggingConnection extends Connection {

    def log(msg: String): Unit = println(s"\t\t[Mock.Conn] $msg")

    private val stmt = new LoggingPreparedStatement

    override def abort(executor: Executor): Unit = log(s"abort(executor=$executor)")

    override def clearWarnings(): Unit = log("clearWarnings()")

    override def close(): Unit = log("close()")

    override def commit(): Unit = log("commit()")

    override def createArrayOf(typeName: String, elements: scala.Array[AnyRef]): sql.Array = {
      log(s"createArrayOf(typeName=$typeName, elements=${elements.mkString(",")})"); null
    }

    override def createBlob(): Blob = {
      log("createBlob()"); null
    }

    override def createClob(): Clob = {
      log("createClob()"); null
    }

    override def createNClob(): NClob = {
      log("createNClob()"); null
    }

    override def createSQLXML(): SQLXML = {
      log("createSQLXML()"); null
    }

    override def createStatement(): Statement = {
      log("createStatement()"); null
    }

    override def createStatement(resultSetType: Int, resultSetConcurrency: Int): Statement = {
      log(s"createStatement(resultSetType=$resultSetType, resultSetConcurrency=$resultSetConcurrency)"); null
    }

    override def createStatement(resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): Statement = {
      log(s"createStatement(resultSetType=$resultSetType, resultSetConcurrency=$resultSetConcurrency, resultSetHoldability=$resultSetHoldability)"); null
    }

    override def createStruct(typeName: String, attributes: scala.Array[AnyRef]): Struct = {
      log(s"createStruct(typeName=$typeName, attributes=${attributes.mkString(",")})"); null
    }

    override def getAutoCommit: Boolean = {
      log("getAutoCommit()"); false
    }

    override def getCatalog: String = {
      log("getCatalog()"); ""
    }

    override def getClientInfo(name: String): String = {
      log(s"getClientInfo(name=$name)"); ""
    }

    override def getClientInfo: Properties = {
      log("getClientInfo()"); new Properties()
    }

    override def getHoldability: Int = {
      log("getHoldability()"); 0
    }

    override def getMetaData: DatabaseMetaData = {
      log("getMetaData()"); null
    }

    override def getNetworkTimeout: Int = {
      log("getNetworkTimeout()"); 0
    }

    override def getSchema: String = {
      log("getSchema()"); ""
    }

    override def getTransactionIsolation: Int = {
      log("getTransactionIsolation()"); 0
    }

    override def getTypeMap: java.util.Map[String, Class[_]] = {
      log("getTypeMap()"); null
    }

    override def getWarnings: SQLWarning = {
      log("getWarnings()"); null
    }

    override def isClosed: Boolean = {
      log("isClosed()"); false
    }

    override def isReadOnly: Boolean = {
      log("isReadOnly()"); false
    }

    override def isValid(timeout: Int): Boolean = {
      log(s"isValid(timeout=$timeout)"); true
    }

    override def isWrapperFor(iface: Class[_]): Boolean = {
      log(s"isWrapperFor($iface)"); false
    }

    override def nativeSQL(sql: String): String = {
      log(s"nativeSQL(sql=$sql)"); sql
    }

    override def prepareCall(sql: String): CallableStatement = {
      log(s"prepareCall(sql=$sql)"); null
    }

    override def prepareCall(sql: String, resultSetType: Int, resultSetConcurrency: Int): CallableStatement = {
      log(s"prepareCall(sql=$sql, resultSetType=$resultSetType, resultSetConcurrency=$resultSetConcurrency)"); null
    }

    override def prepareCall(sql: String, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): CallableStatement = {
      log(s"prepareCall(sql=$sql, resultSetType=$resultSetType, resultSetConcurrency=$resultSetConcurrency, resultSetHoldability=$resultSetHoldability)"); null
    }

    override def prepareStatement(sql: String): PreparedStatement = {
      log(s"prepareStatement(sql=$sql)"); stmt
    }

    override def prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement = {
      log(s"prepareStatement(sql=$sql, autoGeneratedKeys=$autoGeneratedKeys)"); stmt
    }

    override def prepareStatement(sql: String, columnIndexes: scala.Array[Int]): PreparedStatement = {
      log(s"prepareStatement(sql=$sql, columnIndexes=${columnIndexes.mkString(",")})"); stmt
    }

    override def prepareStatement(sql: String, columnNames: scala.Array[String]): PreparedStatement = {
      log(s"prepareStatement(sql=$sql, columnNames=${columnNames.mkString(",")})"); stmt
    }

    override def prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement = {
      log(s"prepareStatement(sql=$sql, resultSetType=$resultSetType, resultSetConcurrency=$resultSetConcurrency)"); stmt
    }

    override def prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): PreparedStatement = {
      log(s"prepareStatement(sql=$sql, resultSetType=$resultSetType, resultSetConcurrency=$resultSetConcurrency, resultSetHoldability=$resultSetHoldability)"); stmt
    }

    override def releaseSavepoint(savepoint: Savepoint): Unit = log(s"releaseSavepoint(savepoint=$savepoint)")

    override def rollback(): Unit = log("rollback()")

    override def rollback(savepoint: Savepoint): Unit = log(s"rollback(savepoint=$savepoint)")

    override def setAutoCommit(autoCommit: Boolean): Unit = log(s"setAutoCommit($autoCommit)")

    override def setCatalog(catalog: String): Unit = log(s"setCatalog($catalog)")

    override def setClientInfo(name: String, value: String): Unit = log(s"setClientInfo(name=$name, value=$value)")

    override def setClientInfo(properties: Properties): Unit = log(s"setClientInfo(properties=$properties)")

    override def setHoldability(holdability: Int): Unit = log(s"setHoldability($holdability)")

    override def setNetworkTimeout(executor: Executor, milliseconds: Int): Unit = log(s"setNetworkTimeout(executor=$executor, milliseconds=$milliseconds)")

    override def setReadOnly(readOnly: Boolean): Unit = log(s"setReadOnly($readOnly)")

    override def setSavepoint(): Savepoint = {
      log("setSavepoint()"); null
    }

    override def setSavepoint(name: String): Savepoint = {
      log(s"setSavepoint(name=$name)"); null
    }

    override def setSchema(schema: String): Unit = log(s"setSchema($schema)")

    override def setTransactionIsolation(level: Int): Unit = log(s"setTransactionIsolation($level)")

    override def setTypeMap(map: util.Map[String, Class[_]]): Unit = {
      val size = if (map == null) "null" else map.size().toString; log(s"setTypeMap(size=$size, map=$map)")
    }

    override def unwrap[T](iface: Class[T]): T = {
      log(s"unwrap($iface)"); null.asInstanceOf[T]
    }
  }

}
