name: Scala Assembly CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'

      - name: Run sbt assembly
        run: sbt clean compile assembly

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DBSync-Jar
          path: target/scala-2.13/DBSync_*.jar
          retention-days: 7 # 다운로드 링크 유지 기간 (기본 90일, 최대 7일 등으로 조절 가능)